#!/usr/bin/env node
/**
 * Figma variables → CSS custom properties.
 * Источник: tokens/figma-export/{ic,codd}-{light,dark}.json, typography.json
 * Выход: src/styles/tokens.css, tokens/build/tokens.css
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const exportDir = join(root, 'tokens/figma-export');
const outPaths = [
  join(root, 'src/styles/tokens.css'),
  join(root, 'tokens/build/tokens.css'),
];

const THEME_PALETTES = ['ic-light', 'ic-dark', 'codd-light', 'codd-dark'];

const THEME_SELECTORS = {
  'ic-light': ':root, [data-brand="ic"][data-theme="light"]',
  'ic-dark': '[data-brand="ic"][data-theme="dark"]',
  'codd-light': '[data-brand="codd"][data-theme="light"]',
  'codd-dark': '[data-brand="codd"][data-theme="dark"]',
};

const PX_KEYS = /^(font-size|line-height|spacing|tracking)\//i;
const SKIP_VALUE = /^(Font\(|Effect\()/;

/** Figma path → CSS var (primary/main → --primary-main, disabledBackground → --action-disabled-background) */
export function figmaKeyToCssVar(key) {
  const normalized = key
    .trim()
    .replace(/\//g, '-')
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/\s+/g, '-')
    .toLowerCase();
  return `--${normalized}`;
}

function formatCSSValue(key, value) {
  if (SKIP_VALUE.test(value)) return null;
  if (key === 'typography/font-family') {
    return '"Moscow Sans W", system-ui, -apple-system, "Segoe UI", Roboto, sans-serif';
  }
  if (/^#[0-9a-f]{6,8}$/i.test(value)) return value;
  if (PX_KEYS.test(key)) {
    const n = Number(value);
    if (!Number.isNaN(n)) return n === 0 ? '0' : `${n}px`;
  }
  if (/^font-weight\//i.test(key)) return value;
  return value;
}

function loadExports() {
  const files = readdirSync(exportDir).filter((f) => f.endsWith('.json'));
  const palettes = {};
  let typography = null;
  for (const file of files) {
    const base = file.replace(/\.json$/, '');
    const raw = JSON.parse(readFileSync(join(exportDir, file), 'utf8'));
    const variables = raw.variables ?? raw;
    if (base === 'typography') {
      typography = variables;
    } else {
      palettes[base] = variables;
    }
  }
  return { palettes, typography };
}

function renderVarLines(variables) {
  return Object.entries(variables)
    .map(([key, value]) => {
      const cssValue = formatCSSValue(key, value);
      if (cssValue == null) return null;
      return `  ${figmaKeyToCssVar(key)}: ${cssValue};`;
    })
    .filter(Boolean)
    .sort()
    .join('\n');
}

function renderThemeBlock(selector, variables) {
  return `${selector} {\n${renderVarLines(variables)}\n}`;
}

function renderTypographyBlock(typography) {
  if (!typography) return '';
  return `/* Typography + spacing (brand-agnostic) */\n:root {\n${renderVarLines(typography)}\n}`;
}

function renderSemanticAliases() {
  return `/* Semantic aliases for components */
:root {
  --color-text-primary: var(--text-main-on-surface);
  --color-text-secondary: var(--text-secondary-on-surface);
  --color-text-disabled: var(--text-disabled-on-surface);
  --color-surface-background: var(--surfaces-background);
  --color-surface-1: var(--surfaces-surface-1);
  --color-surface-2: var(--surfaces-surface-2);
  --color-border: var(--outlines-border);
  --color-border-focus: var(--outlines-focused);
  --color-primary: var(--primary-main);
  --color-primary-hover: var(--primary-main-hover);
  --color-error: var(--error-main);
  --color-success: var(--success-main);
  --color-warning: var(--warning-main);
  --font-family-sans: var(--typography-font-family);
}`;
}

function buildCss(palettes, typography) {
  const header = `/* Generated by scripts/build-tokens.mjs — do not edit by hand */
/* Rebuild: npm run tokens:build */
`;
  const blocks = THEME_PALETTES.filter((id) => palettes[id]).map((id) =>
    renderThemeBlock(THEME_SELECTORS[id], palettes[id]),
  );

  const prefersDark = palettes['ic-dark']
    ? `@media (prefers-color-scheme: dark) {
  :root:not([data-theme]):not([data-brand]) {
${renderVarLines(palettes['ic-dark']).replace(/^/gm, '    ').trimEnd()}
  }
}`
    : '';

  return [
    header,
    ...blocks,
    renderTypographyBlock(typography),
    renderSemanticAliases(),
    prefersDark,
    '',
  ]
    .filter(Boolean)
    .join('\n\n');
}

const { palettes, typography } = loadExports();
if (THEME_PALETTES.every((id) => !palettes[id])) {
  console.error('No theme palette JSON in tokens/figma-export/');
  process.exit(1);
}

const css = buildCss(palettes, typography);
mkdirSync(join(root, 'tokens/build'), { recursive: true });
for (const out of outPaths) {
  writeFileSync(out, css, 'utf8');
}
const names = [...THEME_PALETTES.filter((id) => palettes[id]), typography ? 'typography' : null].filter(
  Boolean,
);
console.log(`tokens built: ${names.join(', ')} → ${outPaths.length} files`);
